server:
  port: 8081

spring:
  application:
    name: eureka-client
  kafka:
    bootstrapAddress: kafka:9092
    topic:
      name: testTopic

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    disable-delta: true
